apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-{{ .Values.workloadClusterName }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsRepoUrl }}
    path: registry/clusters/{{ .Values.workloadClusterName }}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 1m
        maxDuration: 15m0s
        factor: 2

