apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.workloadClusterName }}-aws-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.workloadClusterRegion }}
      role: arn:aws:iam::{{ .Values.workloadClusterAccountId }}:role/eso-{{ .Values.workloadClusterName }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-operator
