apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.workloadClusterName }}-infrastructure-wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: wait
        image: dtzar/helm-kubectl:3.19.0
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl wait --for=jsonpath='{.status.conditions[0].status}'='True' workspace/{{ .Values.workloadClusterName }}-infrastructure; do echo "waiting for cluster to provision"; sleep 5; done
      restartPolicy: Never
  backoffLimit: 1



